### ISSUE TITLE
Unable to Remap Controls on Vita/PSP2

### ISSUE THREAD

**Issue by Smoker1** [meetpatty/basiliskii-vita#3]
I tried to edit the default File in the imaps Folder, but I still am unable to use the Buttons as different Letters or even change the R Trigger as the Mouse

**Comment by meetpatty** [comment]
Press select during emulation to open a menu which will allow you to load this mapping. Default is probably a poor name since the default controls are hard coded in the emulator. The Default file is just a copy of these hard coded button mappings (But can be changed and used to override these mappings).

**Comment by Smoker1** [comment]
Works. Thank you. Had to Create a new File.
